# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea995b083e4503927426ddf89457a316aa5375c09f89934a051c0cdc3239c855b998d0f05cf90223b2424ccd6d197c3524f76c91eb825ab8f0f7959517705b27

test:
  secret_key_base: 8ff0639f48c1c0c79244325a94ba6dfd8b65ed67786ff64dfca134f66499984a9eac56e0bcf97bddbc0e6a7c14c15a6db714ecc1664d5d228c07cf065505b1f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
